/**
 * Transcript acquisition — YouTube caption track only (no STT).
 *
 * Strategy (ported from the proven youtube-transcript-api approach):
 * 1. Read INNERTUBE_API_KEY from the watch page
 * 2. POST youtubei/v1/player with ANDROID client context
 *    → returns caption baseUrls that work WITHOUT PO tokens
 * 3. Prefer the video's default/native caption language (e.g. Hindi stays Hindi)
 *    Manual tracks first, then ASR — never force-translate the transcript.
 * 4. Fetch timedtext (never re-serialize signed URLs)
 * AI answers/topics stay English via LLM prompts (separate from caption language).
 *
 * Why not WEB player response / page captionTracks?
 * WEB tracks often include `&exp=xpe`, which requires a PO token and
 * returns empty bodies in the browser — that was the "Fetch failed" bug.
 */

import type { RawCaptionSegment } from "../types/schema";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface CaptionTrackInfo {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  baseUrl: string;
}

export interface TranscriptFetchResult {
  videoId: string;
  segments: RawCaptionSegment[];
  captionTrackHash: string;
  track: CaptionTrackInfo;
}

export class NoCaptionsError extends Error {
  readonly code = "NO_CAPTIONS" as const;

  constructor(videoId: string, message?: string) {
    super(
      message ??
        `No captions available for video ${videoId}. Speech-to-text fallback is out of scope for Phase 1.`
    );
    this.name = "NoCaptionsError";
  }
}

export class TranscriptFetchError extends Error {
  readonly code = "TRANSCRIPT_FETCH_ERROR" as const;

  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "TranscriptFetchError";
  }
}

// ---------------------------------------------------------------------------
// Innertube / caption shapes
// ---------------------------------------------------------------------------

/** Matches youtube-transcript-api _settings.INNERTUBE_CONTEXT — force English UI/captions locale */
const INNERTUBE_CONTEXT = {
  client: {
    clientName: "ANDROID",
    clientVersion: "20.10.38",
    hl: "en",
    gl: "US",
  },
} as const;

const FALLBACK_INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";

interface YtCaptionTrack {
  baseUrl: string;
  languageCode?: string;
  kind?: string;
  /** e.g. "a.en" for English ASR */
  vssId?: string;
  name?:
    | string
    | { simpleText?: string; runs?: Array<{ text?: string }> };
  isTranslatable?: boolean;
}

interface YtCaptionsJson {
  captionTracks?: YtCaptionTrack[];
  translationLanguages?: unknown[];
}

interface YtPlayerResponse {
  playabilityStatus?: {
    status?: string;
    reason?: string;
  };
  videoDetails?: { videoId?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: YtCaptionsJson;
  };
}

interface Json3Seg {
  utf8?: string;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Json3Seg[];
}

interface Json3Captions {
  events?: Json3Event[];
}

const BRIDGE_SOURCE = "videosearch-ai-bridge";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function fetchTranscript(
  videoId: string
): Promise<TranscriptFetchResult> {
  if (!videoId || !/^[\w-]{6,}$/.test(videoId)) {
    throw new TranscriptFetchError(`Invalid YouTube video id: ${videoId}`);
  }

  console.info("[VideoSearch AI] fetchTranscript: start (innertube ANDROID)", videoId);

  const apiKey = await resolveInnertubeApiKey(videoId);
  console.info("[VideoSearch AI] innertube key:", apiKey.slice(0, 12) + "…");

  const player = await fetchInnertubePlayer(videoId, apiKey);
  assertPlayable(player, videoId);

  const captionsJson = player.captions?.playerCaptionsTracklistRenderer;
  const tracks = (captionsJson?.captionTracks ?? []).filter(
    (t) => typeof t.baseUrl === "string" && t.baseUrl.length > 0
  );

  console.info(
    "[VideoSearch AI] tracks:",
    tracks.length,
    tracks.slice(0, 8).map((t) => ({
      lang: t.languageCode,
      kind: t.kind ?? "manual",
      name: trackDisplayName(t),
      poToken: t.baseUrl.includes("exp=xpe"),
    }))
  );

  if (tracks.length === 0) {
    throw new NoCaptionsError(videoId);
  }

  // Prefer tracks that do NOT require PO token
  const usable = tracks.filter((t) => !t.baseUrl.includes("exp=xpe"));
  const pool = usable.length > 0 ? usable : tracks;

  if (usable.length === 0) {
    console.warn(
      "[VideoSearch AI] All tracks require PO token (exp=xpe). Will try anyway."
    );
  }

  const selected = selectDefaultCaptionTrack(pool);
  // youtube-transcript-api strips a default fmt=srv3 if present
  const baseUrl = selected.baseUrl.replace("&fmt=srv3", "");

  console.info("[VideoSearch AI] selected caption track (native/default):", {
    lang: selected.languageCode,
    kind: selected.kind ?? "manual",
    name: trackDisplayName(selected),
  });

  const { body, usedLabel } = await fetchCaptionBodyRobust(baseUrl);
  console.info(
    "[VideoSearch AI] caption body bytes:",
    body.length,
    "format:",
    usedLabel
  );

  const segments = parseCaptionBody(body);
  if (segments.length === 0) {
    throw new TranscriptFetchError(
      `Parsed 0 segments from caption body (${body.length} bytes, format ${usedLabel}).`
    );
  }

  const trackInfo: CaptionTrackInfo = {
    languageCode: selected.languageCode ?? "und",
    name: trackDisplayName(selected),
    isAutoGenerated: selected.kind === "asr",
    baseUrl,
  };

  const captionTrackHash = await hashCaptionTrack(trackInfo);

  console.info(
    "[VideoSearch AI] fetchTranscript: OK —",
    segments.length,
    "segments"
  );

  return {
    videoId,
    segments,
    captionTrackHash,
    track: trackInfo,
  };
}

// ---------------------------------------------------------------------------
// Innertube
// ---------------------------------------------------------------------------

async function resolveInnertubeApiKey(videoId: string): Promise<string> {
  // 1) MAIN-world bridge (ytcfg on the live page)
  const fromBridge = await requestFromPageBridge<{ apiKey?: string | null }>(
    "GET_INNERTUBE_KEY",
    1500
  );
  if (fromBridge?.apiKey) return fromBridge.apiKey;

  // 2) Inline scripts already in the DOM
  const fromDom = extractApiKeyFromHtml(document.documentElement.innerHTML);
  if (fromDom) return fromDom;

  // 3) Fetch watch HTML
  try {
    const html = await fetchWatchHtml(videoId);
    const fromHtml = extractApiKeyFromHtml(html);
    if (fromHtml) return fromHtml;
  } catch (err) {
    console.warn("[VideoSearch AI] watch HTML fetch for API key failed:", err);
  }

  console.warn(
    "[VideoSearch AI] using fallback INNERTUBE_API_KEY (page key not found)"
  );
  return FALLBACK_INNERTUBE_KEY;
}

function extractApiKeyFromHtml(html: string): string | null {
  const m = html.match(/"INNERTUBE_API_KEY"\s*:\s*"([a-zA-Z0-9_-]+)"/);
  return m?.[1] ?? null;
}

async function fetchWatchHtml(videoId: string): Promise<string> {
  const res = await fetch(
    `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`,
    {
      credentials: "include",
      headers: { Accept: "text/html", "Accept-Language": "en-US" },
    }
  );
  if (!res.ok) {
    throw new TranscriptFetchError(
      `Watch page HTTP ${res.status} for ${videoId}`
    );
  }
  // Decode HTML entities similar to youtube-transcript-api (unescape)
  return decodeHtmlEntities(await res.text());
}

async function fetchInnertubePlayer(
  videoId: string,
  apiKey: string
): Promise<YtPlayerResponse> {
  const url = `https://www.youtube.com/youtubei/v1/player?key=${encodeURIComponent(apiKey)}`;

  let res: Response;
  try {
    res = await fetch(url, {
      method: "POST",
      credentials: "include",
      headers: {
        "Content-Type": "application/json",
        "Accept-Language": "en-US",
      },
      body: JSON.stringify({
        context: INNERTUBE_CONTEXT,
        videoId,
      }),
    });
  } catch (err) {
    throw new TranscriptFetchError(
      `Innertube network error: ${stringifyErr(err)}`,
      { cause: err }
    );
  }

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new TranscriptFetchError(
      `Innertube player HTTP ${res.status}: ${text.slice(0, 120)}`
    );
  }

  try {
    return (await res.json()) as YtPlayerResponse;
  } catch (err) {
    throw new TranscriptFetchError("Innertube returned non-JSON body", {
      cause: err,
    });
  }
}

function assertPlayable(player: YtPlayerResponse, videoId: string): void {
  const status = player.playabilityStatus?.status;
  if (!status || status === "OK") return;

  const reason = player.playabilityStatus?.reason ?? status;
  if (status === "LOGIN_REQUIRED") {
    throw new TranscriptFetchError(
      `YouTube requires login for this video (${reason}). Open the video while signed in and retry.`
    );
  }
  if (status === "UNPLAYABLE" || status === "ERROR") {
    // Still allow captions if present; only throw if we have nothing later
    console.warn(
      "[VideoSearch AI] playability",
      status,
      reason,
      "— continuing if captions exist"
    );
    return;
  }
  console.warn("[VideoSearch AI] playability status:", status, reason, videoId);
}

// ---------------------------------------------------------------------------
// Page bridge helper
// ---------------------------------------------------------------------------

function requestFromPageBridge<T>(
  type: string,
  timeoutMs: number
): Promise<T | null> {
  return new Promise((resolve) => {
    const requestId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;

    const onMessage = (event: MessageEvent) => {
      if (event.source !== window) return;
      const data = event.data;
      if (!data || data.source !== BRIDGE_SOURCE) return;
      if (data.type !== `${type}_RESULT`) return;
      if (data.requestId !== requestId) return;
      window.removeEventListener("message", onMessage);
      window.clearTimeout(timer);
      resolve((data.payload as T) ?? null);
    };

    window.addEventListener("message", onMessage);
    window.postMessage({ source: BRIDGE_SOURCE, type, requestId }, "*");

    const timer = window.setTimeout(() => {
      window.removeEventListener("message", onMessage);
      resolve(null);
    }, timeoutMs);
  });
}

// ---------------------------------------------------------------------------
// Track selection — use the video's default / original language
// (Hindi video → Hindi captions; English video → English captions)
// Do NOT force-translate the transcript. AI answers stay English separately.
// ---------------------------------------------------------------------------

/**
 * Pick the default caption track as YouTube would:
 * 1. Manually created tracks first (creator language), keep YouTube order
 * 2. Else auto-generated (ASR) first track (usually the spoken language)
 */
function selectDefaultCaptionTrack(tracks: YtCaptionTrack[]): YtCaptionTrack {
  if (tracks.length === 0) {
    throw new TranscriptFetchError("No caption tracks to select.");
  }

  const manual = tracks.filter((t) => t.kind !== "asr");
  if (manual.length > 0) {
    // YouTube usually lists the primary/default language first among manuals
    return manual[0];
  }

  // ASR only — first track is typically the spoken language (e.g. hi, en)
  return tracks[0];
}

function trackDisplayName(track: YtCaptionTrack): string {
  const name = track.name;
  if (typeof name === "string") return name;
  if (name && typeof name === "object") {
    if (name.simpleText) return name.simpleText;
    if (name.runs?.[0]?.text) return name.runs[0].text;
  }
  return track.languageCode ?? "unknown";
}

// ---------------------------------------------------------------------------
// Caption body fetch — never re-serialize signed URLs
// ---------------------------------------------------------------------------

function appendQueryParam(baseUrl: string, key: string, value: string): string {
  if (new RegExp(`[?&]${key}=`).test(baseUrl)) return baseUrl;
  const sep = baseUrl.includes("?") ? "&" : "?";
  return `${baseUrl}${sep}${key}=${value}`;
}

async function fetchCaptionBodyRobust(
  baseUrl: string
): Promise<{ body: string; usedLabel: string }> {
  const candidates: Array<{ url: string; label: string }> = [
    { url: appendQueryParam(baseUrl, "fmt", "json3"), label: "json3" },
    { url: baseUrl, label: "xml-default" },
    { url: appendQueryParam(baseUrl, "fmt", "srv3"), label: "srv3" },
    { url: appendQueryParam(baseUrl, "fmt", "vtt"), label: "vtt" },
  ];

  const errors: string[] = [];

  for (const { url, label } of candidates) {
    try {
      const res = await fetch(url, {
        credentials: "include",
        headers: { "Accept-Language": "en-US", Accept: "*/*" },
      });
      if (!res.ok) {
        errors.push(`${label}: HTTP ${res.status}`);
        continue;
      }
      const body = await res.text();
      if (!body.trim()) {
        errors.push(`${label}: empty body`);
        continue;
      }
      const t = body.trim();
      if (
        t.startsWith("{") ||
        t.startsWith("<") ||
        t.startsWith("WEBVTT")
      ) {
        return { body, usedLabel: label };
      }
      errors.push(`${label}: bad prefix ${JSON.stringify(t.slice(0, 30))}`);
    } catch (err) {
      errors.push(`${label}: ${stringifyErr(err)}`);
    }
  }

  throw new TranscriptFetchError(
    `Caption download failed. ${errors.join(" · ")}`
  );
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

export function parseCaptionBody(body: string): RawCaptionSegment[] {
  const trimmed = body.trim();
  if (!trimmed) return [];

  if (trimmed.startsWith("WEBVTT")) return parseVtt(trimmed);

  if (trimmed.startsWith("{")) {
    try {
      return parseJson3(JSON.parse(trimmed) as Json3Captions);
    } catch {
      // fall through
    }
  }

  if (trimmed.startsWith("<") || trimmed.includes("<text")) {
    return parseXmlCaptions(trimmed);
  }

  try {
    return parseJson3(JSON.parse(trimmed) as Json3Captions);
  } catch {
    return [];
  }
}

function parseJson3(data: Json3Captions): RawCaptionSegment[] {
  const segments: RawCaptionSegment[] = [];
  for (const event of data.events ?? []) {
    if (!event.segs?.length) continue;
    const text = event.segs
      .map((s) => s.utf8 ?? "")
      .join("")
      .replace(/\n+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    const startTime = (event.tStartMs ?? 0) / 1000;
    const endTime = startTime + (event.dDurationMs ?? 0) / 1000;
    segments.push({
      startTime,
      endTime: endTime > startTime ? endTime : startTime,
      text: decodeHtmlEntities(text),
    });
  }
  return segments;
}

function parseXmlCaptions(xml: string): RawCaptionSegment[] {
  const doc = new DOMParser().parseFromString(xml, "text/xml");
  if (doc.querySelector("parsererror")) return [];

  const nodes = doc.querySelectorAll("text");
  const segments: RawCaptionSegment[] = [];

  nodes.forEach((node) => {
    const start = parseFloat(node.getAttribute("start") ?? "0");
    const dur = parseFloat(node.getAttribute("dur") ?? "0");
    const text = decodeHtmlEntities(node.textContent ?? "")
      .replace(/\n+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (!text || Number.isNaN(start)) return;
    segments.push({
      startTime: start,
      endTime: !Number.isNaN(dur) && dur > 0 ? start + dur : start,
      text,
    });
  });

  return segments;
}

function parseVtt(vtt: string): RawCaptionSegment[] {
  const segments: RawCaptionSegment[] = [];
  const blocks = vtt.replace(/\r\n/g, "\n").split(/\n\n+/);

  for (const block of blocks) {
    const lines = block.split("\n").filter((l) => l.trim().length > 0);
    const timeIdx = lines.findIndex((l) => l.includes("-->"));
    if (timeIdx === -1) continue;
    const [startRaw, endRaw] = lines[timeIdx].split("-->").map((s) => s.trim());
    const startTime = parseVttTimestamp(startRaw.split(/\s+/)[0]);
    const endTime = parseVttTimestamp(endRaw.split(/\s+/)[0]);
    if (startTime === null || endTime === null) continue;
    const text = lines
      .slice(timeIdx + 1)
      .join(" ")
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    segments.push({
      startTime,
      endTime,
      text: decodeHtmlEntities(text),
    });
  }
  return segments;
}

function parseVttTimestamp(ts: string): number | null {
  const parts = ts.split(":");
  if (parts.length < 2 || parts.length > 3) return null;
  let hours = 0;
  let minutes = 0;
  let seconds = 0;
  if (parts.length === 3) {
    hours = parseInt(parts[0], 10);
    minutes = parseInt(parts[1], 10);
    seconds = parseFloat(parts[2]);
  } else {
    minutes = parseInt(parts[0], 10);
    seconds = parseFloat(parts[1]);
  }
  if ([hours, minutes, seconds].some((n) => Number.isNaN(n))) return null;
  return hours * 3600 + minutes * 60 + seconds;
}

function decodeHtmlEntities(text: string): string {
  // textarea trick handles the full entity set in the browser
  if (typeof document !== "undefined") {
    const el = document.createElement("textarea");
    el.innerHTML = text;
    return el.value;
  }
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n: string) =>
      String.fromCharCode(parseInt(n, 10))
    )
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h: string) =>
      String.fromCharCode(parseInt(h, 16))
    )
    .replace(/\\u0026/g, "&");
}

function stringifyErr(err: unknown): string {
  if (err instanceof Error) return err.message;
  return String(err);
}

async function hashCaptionTrack(track: CaptionTrackInfo): Promise<string> {
  const material = [
    track.languageCode,
    track.isAutoGenerated ? "asr" : "manual",
    track.name,
  ].join("|");
  const data = new TextEncoder().encode(material);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
    .slice(0, 16);
}
